### ISSUE TITLE
subprocess.Popen error

### ISSUE THREAD

**Issue by maolun** [elzbth/jitterbug#10]
I am trying to run jitterbug on Arabidopsis genomes, but an subprocess error occurred that prevents the program from running. It seems that one argument was missing but I can't figure out which one. I wonder if anyone has the same problem and was able to fix it. Thank you.

I have tried python 2.7.9 and 2.7.10 but the same error occurred. 

Traceback (most recent call last):
  File "/home-3/maolun/jitterbug-master/jitterbug.py", line 140, in <module>
    main(sys.argv[1:])
  File "/home-3/maolun/jitterbug-master/jitterbug.py", line 136, in main
    args.numCPUs, args.bin_size, args.minMAPQ, generate_test_bam, args.pre_filter, args.conf_lib_stats, mem, args.min_cluster_size)
  File "/home-3/maolun/jitterbug-master/Run_TE_ID_reseq.py", line 248, in run_jitterbug
    int_bed_reads_select = subprocess.Popen(args)
  File "/cm/shared/apps/python/2.7.9/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/cm/shared/apps/python/2.7.9/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Best regards,
Mao-Lun

**Comment by mbosio85** [comment]
Hi,

in the lines previous to that the args of Popen are defined:

> args = ["samtools", "view", "-hb", "-L", bed_file_name, "-o", ins_regions_bam_name, psorted_bamfile_name]
> 247	    # open subprocess 
> 248	    int_bed_reads_select = subprocess.Popen(args)

Can you check if the files referring to [bed_file_name and ins_regions_bam_name]  exist because it's the likely source of the OSError:[Errno 2] No such file or directory

Mattia

**Comment by maolun** [comment]
Hi Mattia,

Thanks for the response.  It turns out that it has something to do with multiple version of python installed in the cluster I am using at my institute.  I have to change the shebang line in jitterbug.py to refer to the correct python version. 

Mao-Lun

**Comment by maolun** [comment]
Update information. I finally figured out what the error is about. It is because the samtools is not available that cause the subprocess.Popen(args) having an error of 'no such file or directory'.  

I would suggest maybe adding a line for checking the availability of samtools in the script. 

Mao-Lun

**Comment by mbosio85** [comment]
Thanks we will add a check for it
