### ISSUE TITLE
Error when I launch the script

### ISSUE THREAD

**Issue by Leelouh** [elzbth/jitterbug#12]
Hi,

I tried to launch the script jitterbug.py without arguments, just to see if the installation was ok. 
But I have this two error : 

> Traceback (most recent call last):
>  File "./jitterbug.py", line 21, in <module>
>    from Run_TE_ID_reseq import *
>  File "/home/lhelou/local/jitterbug/Run_TE_ID_reseq.py", line 6, in <module>
>    import pysam
>ImportError: No module named pysam

jitterbug needs to be launch with Python2 right?

Can you help me?
Thank you!

**Comment by mbosio85** [comment]
Hi,

yes, it requires to be with python2, it looks like you don't have pysam in you python librarires
