### ISSUE TITLE
Cannot import name csamtools

### ISSUE THREAD

**Issue by fbemm** [elzbth/jitterbug#2]
I got the following error running jitterbug on a Ubuntu 14.04:

Traceback (most recent call last):
  File "./jitterbug.py", line 21, in <module>
    from Run_TE_ID_reseq import *
  File "/ebio/abt6_projects9/abt6_software/bin/jitterbug/Run_TE_ID_reseq.py", line 12, in <module>
    from pysam import csamtools
ImportError: cannot import name csamtools

Dependencies are installed. I compiled pysam from source and installed it over pip. Both attempts show the same behavior. Any idea what is going on. pysam is version 0.9.0! Thx for help.

**Comment by mbosio85** [comment]
Hi,

I don't personally know how to fix it but here there's some hints from someone with the same problem with pysam

https://www.biostars.org/p/151219/

Hope it's useful

**Comment by sidratools** [comment]
Hi Felix,
To resolve this "ImportError: cannot import name csamtools" issue, you need to build the pysam. Note that, your selected pysam version should have csamtools.pyx (Example: pysam-0.7.5 or pysam-0.8.1 may be used).

**Comment by jokelley** [comment]
Hi, We are trying to run jitterbug and we are getting the error "ImportError: cannot import name csamtools". We would like to use this tool but are unable to get it working. We have pip installed all of the required dependencies (pysam, psutil, pybedtools, numpy)

**Comment by mbosio85** [comment]
Hi,
did you check the version of pysam you have installed as advised by @sidratools ?

> Hi Felix,
To resolve this "ImportError: cannot import name csamtools" issue, you need to build the pysam. Note that, your selected pysam version should have csamtools.pyx (Example: pysam-0.7.5 or pysam-0.8.1 may be used).

or try to check this link
[https://www.biostars.org/p/151219/](https://www.biostars.org/p/151219/)
