### ISSUE TITLE
typo on bin size?

### ISSUE THREAD

**Issue by burnsro** [elzbth/jitterbug#7]
taken from here:

example usage: run with bam file, write to specified directory with specified prefix. Parallelize: use 8 threads, separating by **50 Kbp** bins
jitterbug.py --numCPUs 8  --bin_size 50000000 --output_prefix /path/to/my/dir/prefix sample.bam te_annot.gff3

50 Kb = 50,000
50 Mb = 50,000,000

Also this is quite a large bin size, is that standard?

**Comment by mbosio85** [comment]
Hi,

you're right it's 50Mb :) thanks for noticing.
It's a bin size to split the file processing, it does not merge data in 50Mb windows. 
Simply data are processed in windows of 50Mb, so the processing can be parallelized without being dominated by data transfer (it would happen with much smaller windows).

And nope, it's not standard, it's a simple decision made after in-house tests to split the work

thanks, I'll correct it in the next commit.

Mattia

**Comment by burnsro** [comment]
OK, from doing test runs (with window size increasing from 1Kb to 50Kb) using Arabidopsis data cited in the Jitterbug paper, I find a correlation between how many TEs are found and bin size. For example, 1Kb bin size produced 6 TE insertions being found and 50Kb windows produced 1000 insertions.

**Comment by mbosio85** [comment]
Hi,

sorry for the delay.
Do you see any saturation effect? We included the windowing with big windows to parallelize the work. 
Jitterbug does generate clusters looking within a window and smaller window give less opportunity to find clusters falling in the same interval.

We prefer to include "as much as possible" in the windowing phase, and later filter by quality metrics etc to improve precision .

Hope it helps
Mattia

**Comment by burnsro** [comment]
What would these quality metrics be? Coverage?

**Comment by mbosio85** [comment]
Hi, 

the quality metrics are those specified in the filter, like number of reads supporting the TEI, TEI size, consistency of supporting TEI reads if they all come from the same type .
Mattia
