### ISSUE TITLE
Multi sample calling error

### ISSUE THREAD

**Issue by clemgoub** [elzbth/jitterbug#9]
Hello, 

I am encountering an issue while trying to do a multi-sample calling. I did successfully called the polymorphic TE in 15 samples independently, then as indicated in the tutorial, filtered the gff3 using the filtering tool with the automatically generated parameter files. I am now using the multisample_caller.sh script as detailed in the manual, but I have the following error:

Error: Sorted input specified, but the file MS_calling_.all_filtered.gff3 has the following out of order record
chr10	jitterbug	TE_insertion	53046175	53046292	.	.	.	supporting_fwd_reads=21; supporting_rev_reads=16; cluster_pair_ID=167; lib=None; Inserted_TE_tags_fwd=AluYe5, AluYc, AluY, AluYe6, AluYk3, AluYf1, AluSc, AluSx1; Inserted_TE_tags_rev=AluYe5, AluYk3, AluYk2, AluY, AluSx; fwd_cluster_span=234; rev_cluster_span=327; softclipped_pos=(53046206, 53046215); softclipped_support=3; het_core_reads=0; zygosity=1.000; predicted_superfam=AluYe5
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*

The process seemed to have stopped and only the file <output.suffix>.all_filtered.gff3 is not empty.
I have to add that the filtering has been very drastic, since only one or two line has been kept per file out of ~2000 or more initial calls!

Thanks for your reply!

Clément

**Comment by mbosio85** [comment]
Hi

there was a bug in multisample tool because mergeBed require the input file to be sorted.
Now I added an extra line, can you try to update the code with git pull and rerun it?

About the filtering strictness you can manually edit the filtering parameters (also removing them) if you want from the filter text file.

Mattia

**Comment by clemgoub** [comment]
Hi Mattia!

Excellent it worked lika a charm!

Thanks a lot!
